### PR TITLE
Update story-of-a-tensor-torch.py

### PR DESCRIPTION
**Pull request by ncarandini**
Warning: I'm a rookie on python and torch, so I've modified the source on VS Code using the "hello-ai-world-torch.py" file as a guide and many requests to GitHub Copilot selecting portion of the original code and asking "Do the same with Torch" 😄 After some iteration I made it working. I wish I coud use a Mac to check if my version returns equivalent output, especially regarding output of weight and bias parameters.

### CODE REVIEW

**Comment by neobundy** [comment]
I think there might be a bit of confusion regarding the purpose of this repository.

Firstly, I'd recommend taking a look here: [CONTRIBUTING.md](https://github.com/neobundy/Deep-Dive-Into-AI-With-MLX-PyTorch/blob/master/CONTRIBUTING.md)

Secondly, the chapter in question already includes the MLX equivalent, which you can find here: [story-of-a-tensor-mlx.py](https://github.com/neobundy/Deep-Dive-Into-AI-With-MLX-PyTorch/blob/master/book/001-story-of-a-tensor/story-of-a-tensor-mlx.py)

Lastly, it's important to note that current GPT models, including Copilot, aren't informed about MLX. So, it's better not to rely on them for this – they're primarily focused on completing tasks based on their training.

**Comment by neobundy** [comment]
I don't know how I replaced the torch code with MLX. I've fixed it now.
Just a heads-up, torch and mlx look pretty similar, so it seems like Copilot can handle it. But honestly, it falls short. Most of the code Copilot translates ends up with loads of errors, especially with complex code. So, don't rely on it for now. Remember, Copilot is based on GPT-4, which came before MLX, and it hasn't been trained on MLX data. Also, MLX really doesn't have much data. The documentation and examples are pretty weak for any model to get trained on.

You might get some general ideas from it, but not actual MLX code. At best, it'll just end up leaving you confused.

**Comment by neobundy** [comment]
Just to be clear, I'm not turning down your assistance. I'm working on a book and need to handle it myself. Your feedback would be great, but pull requests aren't what this repo is for. Also, you can't disable pull requests in public repos.

**Comment by ncarandini** [comment]
My fault, I didn't read the contributing.md, sorry for that.
So I'll continue to submit issues (I've found another 😺) but no PR.
Can't wait for chapiter 2, meanwhile I'll keep reading essays.

**Pull request closed without merging**
